### ISSUE TITLE
can't install - no release version

### ISSUE THREAD

**Issue by rcrooks** [Emonadeo/Tanne#2]
Hi @Emonadeo just to let you know, VSCode won't install this because there is no release version (so the message says). That would be in the package.json

**Comment by emonadeo** [comment]
You have to click the little dropdown arrow on the right side of the Install button and select "Install pre-release".

I know it's unintuitive for now but the theme is not 100% implemented yet so I didn't want to do a full release. I wish VSCode would handle the button differently.

(As to why I published it in the first place, it's mainly to make it easier for friends, who help me beta test it, to download it. But it's also nice to see other people use it.)
